name: Manual APK Build and Release

on:
  push:
    tags:
      - 'v*'  # Manual trigger: git tag v1.0.x && git push origin v1.0.x

permissions:
  contents: write
  actions: read

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.2'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build APK
      run: flutter build apk --release
      
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT
      
    - name: Create Release and Upload APK
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Fleet Release ${{ github.ref_name }}
        body: |
          🚕 **Taxi Fleet Manual Release** 🚕
          
          **Version**: ${{ github.ref_name }}
          **Build Date**: ${{ steps.date.outputs.date }}
          
          ### Manual Deployment Instructions:
          1. Download the APK file below
          2. Manually install on taxi tablets
          3. Auto-update system is DISABLED for manual control
          
          ### Fleet Information:
          - **Target**: 200 taxi tablets
          - **Update method**: Manual installation
          - **APK size**: ~60MB
          
          **📱 Download APK and manually install on tablets**
        files: |
          ./build/app/outputs/flutter-apk/app-release.apk
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}